name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          [
            "fedora:30",
            "fedora:31",
          ]
        include:
          - image: "fedora:30"
            name: "fedora-30"
            arch: "amd64"
          - image: "fedora:31"
            name: "fedora-31"
            arch: "amd64"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Build the Package
        run: |
          docker create --name build -it ${{ matrix.image }} sh -c "yum install -y sudo && useradd builder && echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder && chown -R builder:builder /build && su -c /build/build.sh builder"
          docker cp . build:/build
          docker start -a build
          docker rm build
